export const temp_services = [
  {
    id: 1,
    title: "Career Consultation",
    type: "1:1 Call",
    duration: "30 mins",
    price: 1500,
    status: "active",
    createdAt: "2024-01-20",
  },
  {
    id: 2,
    title: "Premium Support",
    type: "Priority DM",
    price: 999,
    status: "active",
    createdAt: "2024-01-19",
  },
  // Add more initial data for testing
];
export const serviceExamples = {
  "1-1-call": [
    {
      title: "Career Consultation",
      duration: "30 mins",
      price: "₹1,500",
      highlight: "Most Popular",
      description: "One-on-one career guidance and resume review",
    },
    {
      title: "Therapy Session",
      duration: "45 mins",
      price: "₹2,000",
      description: "Personal counseling and mental wellness",
    },
    {
      title: "Technical Interview Prep",
      duration: "60 mins",
      price: "₹2,500",
      description: "Mock interviews and feedback sessions",
    },
    {
      title: "Fitness Consultation",
      duration: "45 mins",
      price: "₹1,200",
      highlight: "New",
      description: "Personalized workout and nutrition planning",
    },
    {
      title: "Business Strategy",
      duration: "60 mins",
      price: "₹3,000",
      highlight: "Premium",
      description: "Strategic business planning and growth consulting",
    },
  ],
  "priority-dm": [
    {
      title: "Weekly DM Access",
      price: "₹499",
      highlight: "Best Value",
      description: "Direct message support with 24hr response time",
    },
    {
      title: "VIP Monthly Support",
      price: "₹1,999",
      description: "Priority messaging with instant notifications",
    },
    {
      title: "Emergency Support",
      price: "₹2,999",
      highlight: "Premium",
      description: "24/7 priority access with 15-min response guarantee",
    },
    {
      title: "Student Support",
      price: "₹299",
      highlight: "Special",
      description: "Academic queries and guidance support",
    },
  ],
  webinar: [
    {
      title: "Digital Marketing Masterclass",
      duration: "120 mins",
      price: "₹999",
      platform: "Zoom",
      highlight: "Bestseller",
      description: "Learn SEO, SEM, and Social Media Marketing",
    },
    {
      title: "Financial Planning Workshop",
      duration: "90 mins",
      price: "₹799",
      platform: "Google Meet",
      description: "Investment strategies and portfolio management",
    },
    {
      title: "Tech Interview Bootcamp",
      duration: "180 mins",
      price: "₹1,499",
      platform: "Zoom",
      highlight: "High Demand",
      description: "Intensive coding interview preparation",
    },
    {
      title: "Content Creation Workshop",
      duration: "120 mins",
      price: "₹699",
      platform: "Microsoft Teams",
      description: "Master social media content creation",
    },
    {
      title: "Leadership Excellence",
      duration: "150 mins",
      price: "₹1,299",
      platform: "Zoom",
      highlight: "Executive",
      description: "Advanced leadership and management skills",
    },
  ],
  "digital-product": [
    {
      title: "Complete Web Development Guide",
      type: "E-book",
      price: "₹2,999",
      highlight: "Featured",
      description: "300+ pages of practical tutorials and projects",
    },
    {
      title: "Fitness Transformation Course",
      type: "Video Course",
      price: "₹1,499",
      description: "12-week program with meal plans",
    },
    {
      title: "Stock Market Mastery",
      type: "Course Bundle",
      price: "₹4,999",
      highlight: "Premium",
      description: "Complete trading and investment course with tools",
    },
    {
      title: "Digital Art Collection",
      type: "Resource Pack",
      price: "₹799",
      highlight: "New",
      description: "500+ premium design assets and templates",
    },
    {
      title: "Language Learning Pack",
      type: "Interactive Course",
      price: "₹1,999",
      description: "Self-paced language learning with audio guides",
    },
    {
      title: "Business Plan Templates",
      type: "Resource Bundle",
      price: "₹899",
      highlight: "Startup Special",
      description: "20+ customizable business plan templates",
    },
  ],
};
export const serviceTypes = [
  {
    id: "1-1-call",
    title: "1:1 Call",
    description: "Conduct 1:1 video sessions",
    icon: "🎥",
    color: "bg-blue-50 hover:bg-blue-100",
    borderColor: "border-blue-200",
  },
  {
    id: "priority-dm",
    title: "Priority DM",
    description: "Setup your priority inbox",
    icon: "📨",
    color: "bg-purple-50 hover:bg-purple-100",
    borderColor: "border-purple-200",
  },
  {
    id: "webinar",
    title: "Webinar",
    description: "Host one time or recurring group sessions",
    icon: "👥",
    color: "bg-green-50 hover:bg-green-100",
    borderColor: "border-green-200",
  },
  {
    id: "digital-product",
    title: "Digital Product",
    description: "Sell digital products, courses, paid videos & more",
    icon: "📚",
    color: "bg-orange-50 hover:bg-orange-100",
    borderColor: "border-orange-200",
  },
];
